<a href="https://colab.research.google.com/github/Ragini2424/CognitiveAssignment/blob/main/cognitive_ass4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
'''Q.1 Write a program to create a NumPy 1D-array with 5 elements and perform basic
operations like:
a) Addition of 2 in all the element
b) Multiply 3 with all the elements
c) Divide every element by 2 '''
import numpy as np
a = np.array([1,2,3,4,5])
print (a + 2)
print(a*3)
print(a/2)



[3 4 5 6 7]
[ 3  6  9 12 15]
[0.5 1.  1.5 2.  2.5]


In [2]:
'''Q.2 Questions on Basic NumPy Array:
a) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
b) Find the most frequent value and their indice(s) in the following arrays:
i. x = np.array([1,2,3,4,5,1,2,1,1,1])
ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ])'''

import numpy as np

# (a) Reverse the NumPy array
arr = np.array([1, 2, 3, 6, 4, 5])
reversed_arr = arr[::-1]
print("Reversed array:", reversed_arr)

# (b) Find the most frequent value and its indices
def most_frequent(arr):
    val = max(arr, key=list(arr).count)
    return val, np.where(arr == val)[0]

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])
y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

print("Most frequent in x:", most_frequent(x))
print("Most frequent in y:", most_frequent(y))




Reversed array: [5 4 6 3 2 1]
Most frequent in x: (1, array([0, 5, 7, 8, 9]))
Most frequent in y: (1, array([0, 1, 2]))


In [3]:
'''Q.3 For the given 2-D array arr=np.array([10, 20, 30], [40, 50, 60], [70, 80, 90]), access
elements using row and column indices as follows:
a) Access 1st row, 2nd column
b) Access 3rd row, 1st column '''

import numpy as np

arr = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

print("1st row, 2nd column:", arr[0, 1])
print("3rd row, 1st column:", arr[2, 0])


1st row, 2nd column: 20
3rd row, 1st column: 70


In [4]:
'''Q.4 Write program to create an 1-D NumPy array named <<Your Name>> with evenly
spaced 25 numbers from 10 to 100 using linspace(). Print the dimensions of the array,
shape, total elements, the data type of each element and total number of bytes consumed
by the array. Find the transpose of this array using reshape() attribute. Can we do the same
with T attribute?'''
import numpy as np

Ragini = np.linspace(10, 100, 25)

print("Array:", Ragini)
print("Dimensions of the array:", Ragini.ndim)
print("Shape of the array:", Ragini.shape)
print("Total elements in the array:", Ragini.size)
print("Data type of each element:", Ragini.dtype)
print("Total number of bytes consumed:", Ragini.nbytes)

Ragini_reshaped = Ragini.reshape(25, 1)
Ragini_transposed = Ragini_reshaped.T

print("\nReshaped array (25x1):\n", Ragini_reshaped)
print("\nTransposed array using reshape:\n", Ragini_transposed)

print("\nTrying to use .T on 1-D array:", Ragini.T)



Array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
  85.    88.75  92.5   96.25 100.  ]
Dimensions of the array: 1
Shape of the array: (25,)
Total elements in the array: 25
Data type of each element: float64
Total number of bytes consumed: 200

Reshaped array (25x1):
 [[ 10.  ]
 [ 13.75]
 [ 17.5 ]
 [ 21.25]
 [ 25.  ]
 [ 28.75]
 [ 32.5 ]
 [ 36.25]
 [ 40.  ]
 [ 43.75]
 [ 47.5 ]
 [ 51.25]
 [ 55.  ]
 [ 58.75]
 [ 62.5 ]
 [ 66.25]
 [ 70.  ]
 [ 73.75]
 [ 77.5 ]
 [ 81.25]
 [ 85.  ]
 [ 88.75]
 [ 92.5 ]
 [ 96.25]
 [100.  ]]

Transposed array using reshape:
 [[ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
   47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5   81.25
   85.    88.75  92.5   96.25 100.  ]]

Trying to use .T on 1-D array: [ 10.    13.75  17.5   21.25  25.    28.75  32.5   36.25  40.    43.75
  47.5   51.25  55.    58.75  62.5   66.25  70.    73.75  77.5

In [5]:
import numpy as np

ucs420_Ragini = np.array([[10, 20, 30, 40],
                            [50, 60, 70, 80],
                            [90, 15, 20, 35]])

mean_value = np.mean(ucs420_Ragini)
median_value = np.median(ucs420_Ragini)
max_value = np.max(ucs420_Ragini)
min_value = np.min(ucs420_Ragini)
unique_elements = np.unique(ucs420_Ragini)

print("Mean:", mean_value)
print("Median:", median_value)
print("Max:", max_value)
print("Min:", min_value)
print("Unique Elements:", unique_elements)

# Reshaping the array to four rows and three columns
reshaped_ucs420_Ragini = ucs420_Ragini.reshape(4, 3)
print("\nReshaped Array (4x3):\n", reshaped_ucs420_Ragini)

# Resizing the array to two rows and three columns
resized_ucs420_Ragini = np.resize(ucs420_Ragini, (2, 3))
print("\nResized Array (2x3):\n", resized_ucs420_Ragini)


Mean: 43.333333333333336
Median: 37.5
Max: 90
Min: 10
Unique Elements: [10 15 20 30 35 40 50 60 70 80 90]

Reshaped Array (4x3):
 [[10 20 30]
 [40 50 60]
 [70 80 90]
 [15 20 35]]

Resized Array (2x3):
 [[10 20 30]
 [40 50 60]]
